# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-27 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import text2phenotype.text2phenotype_auth.models.text2phenotype_base


class Migration(migrations.Migration):

    dependencies = [
        ('text2phenotype_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text2phenotypeGroup',
            fields=[
                ('uuid', models.CharField(db_index=True, default=text2phenotype.text2phenotype_auth.models.text2phenotype_base.generate_uuid, max_length=32)),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('application', models.IntegerField(choices=[[1, 1], [2, 2]])),
                ('okta_id', models.CharField(blank=True, max_length=50, null=True)),
                ('users', models.ManyToManyField(related_name='text2phenotype_groups', to='text2phenotype_auth.Text2phenotypeUser')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='text2phenotypegroup',
            unique_together=set([('name', 'application')]),
        ),
        migrations.AlterModelManagers(
            name='text2phenotypegroup',
            managers=[
                ('objects', models.manager.Manager()),
                ('integration_portal', text2phenotype.text2phenotype_auth.models.text2phenotype_group.IntegrationPortalGroupManager()),
                ('sands', text2phenotype.text2phenotype_auth.models.text2phenotype_group.SandsGroupManager()),
            ],
        ),
    ]
