# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-25 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text2phenotype_auth', '0002_auto_20200227_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='text2phenotypeuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
