# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text2phenotype_auth', '0005_text2phenotypeuser_groups_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text2phenotypeuser',
            name='groups_hash',
        ),
    ]
