# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-11 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text2phenotype_auth', '0006_remove_text2phenotypeuser_groups_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='text2phenotypeuser',
            name='is_annotation_tool_visible',
            field=models.BooleanField(default=True),
        ),
    ]
