GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp_credentials.json  # Path where GOOGLE_APPLICATION_CREDENTIALS_JSON is written

# Text2phenotype API flags
MDL_API_DOCUMENT_PROCESSING_CORPUS_ENABLED: True
MDL_API_DOCUMENT_PROCESSING_FILE_ENABLED: True
MDL_API_DOCUMENT_PROCESSING_TEXT_ENABLED: True

MDL_API_OPERATION_APP_INGEST_ENABLED: True
MDL_API_OPERATION_DEID_ENABLED: True
MDL_API_OPERATION_DEMOGRAPHICS_ENABLED: True
MDL_API_OPERATION_OCR_ENABLED: True
MDL_API_OPERATION_ONCOLOGY_ONLY_ENABLED: True
MDL_API_OPERATION_SUMMARY_CLINICAL_ENABLED: True
MDL_API_OPERATION_SUMMARY_ONCOLOGY_ENABLED: True

# Setup application
MDL_COMN_ADDRESS_HOST: ''
MDL_COMN_APPLICATION_NAME: ''

# Setup APM
MDL_COMN_APM_ENABLED: False
MDL_COMN_APM_SECRET_TOKEN: Store in Credstash in deployment
MDL_COMN_APM_SERVER_URL: http://localhost:8200

# Setup AWS
MDL_COMN_AWS_ACCESS_ID: ''
MDL_COMN_AWS_ACCESS_KEY: ''
MDL_COMN_AWS_ENDPOINT_S3: ''
MDL_COMN_AWS_REGION_NAME: us-west-2

# Biomed
MDL_COMN_BIOMED_API_BASE: http://0.0.0.0:8080
MDL_COMN_BIOMED_MAX_DOC_WORD_COUNT: 10000
MDL_COMN_BIOMED_MODELS: ''

MDL_COMN_DEFAULT_QUEUE_SERVICE: RMQ  # Supported values: SQS, RMQ, KUBEMQ
MDL_COMN_DEFAULT_STORAGE_SERVICE: S3  # Supported values: S3
MDL_COMN_STORAGE_CONTAINER_NAME: s3-bucket-name

# Setup Text2phenotype Services
MDL_COMN_DISCHARGE_URL: http://0.0.0.0:5001
MDL_COMN_FEAT_API_BASE: http://0.0.0.0:8081
MDL_COMN_INTAKE_URL: http://0.0.0.0:5000
MDL_COMN_NEURONER_API_BASE: https://0.0.0.0:8082

# Setup KubeMQ
MDL_COMN_KUBEMQ_PORT: 50000
MDL_COMN_KUBEMQ_HOST: localhost
MDL_COMN_KUBEMQ_MESSAGE_VISIBILITY_SECONDS: 30
MDL_COMN_KUBEMQ_MAX_RECEIVE_COUNT: 3
MDL_COMN_KUBEMQ_MESSAGE_EXPIRATION_SECONDS: 43200  # 12 hours

# Setup logging
MDL_COMN_LOG_TO_FILE: True
MDL_COMN_LOGFILE: text2phenotype.log
MDL_COMN_HIPAA_LOGFILE: text2phenotype_hipaa.log
MDL_COMN_HUMAN_READABLE_LOGS: False
MDL_COMN_LOGLEVEL: INFO

MDL_COMN_TEXT2PHENOTYPE_SAMPLES_PATH: ''

# Setup Redis
MDL_COMN_REDIS_AUTH_PASSWORD: password
MDL_COMN_REDIS_AUTH_REQUIRED: True
MDL_COMN_REDIS_LOCK_EXPIRATION: 3

# Setup RabbitMQ
MDL_COMN_RMQ_HOST: localhost
MDL_COMN_RMQ_PORT: 5672
MDL_COMN_RMQ_USERNAME: rmquser
MDL_COMN_RMQ_PASSWORD: rmquser
MDL_COMN_RMQ_MAX_RECEIVE_COUNT: 3
MDL_COMN_RMQ_DEFAULT_EXCHANGE: text2phenotype-default-exchange
MDL_COMN_RMQ_DEFAULT_EXCHANGE_TYPE: x-delayed-message
MDL_COMN_RMQ_HEARTBEAT: 60
MDL_COMN_RMQ_CONNECTION_ATTEMPTS: 3
MDL_COMN_RMQ_CONNECTION_RETRY_DELAY: 2

# Setup Azure OCR
MDL_TASK_OCR_AZURE_ENDPOINT: Store in Credstash in deployment
MDL_TASK_OCR_AZURE_SUBSCRIPTION_KEY: Store in Credstash in deployment
