ENGLISH_STOPWORDS = {'ourselves', 'hers', 'between', 'yourself', 'but', 'again', 'there', 'about', 'once', 'during',
                     'out', 'very', 'having', 'with', 'they', 'own', 'an', 'be', 'some', 'for', 'do', 'its', 'yours',
                     'such', 'into', 'of', 'most', 'itself', 'other', 'of', 'theirs', 'my', 'against', 'a', 'by',
                     'doing', 'it', 'how', 'further', 'was', 'here', 'than', 'the', 'in', 'within', 'to', 'and',
                     "discuss", "concern", "approximate", "estimate", "recent", "update", "per", "maintain", "current",
                     "significant", "show", "shows", "eliminate", "eliminates",
                     "eliminated", "subtype", "revealed", "revealing", "demonstrated", "demonstrating",
                     "demonstrate", "demonstrates", "regarding", "represents", "represent", "represented", "called",
                     "related", "via", "including", "include", "includes", "suggests", "suggest", "suggesting",
                     "showed", "shows", "consider", "causes",
                     "redo", "today", "tomorrow",  "symptomatic",  "elects", "elective",
                     "maternal", "cousin", "paternal", "grandfather", "grandmother", "aunt", "uncle", "familial",
                     "versus", "suspected", "suspect", "diagnose", "must", "may", "should", "without", "with",
                     "possible", "possibly", "possibility", "diagnosed", "likely", "known", "probable", "following",
                     "underwent", "undergo", "previous", "prior", "post", "who", "whose", "probably", "no", "none",
                     "history", "family", "brother", "mother", "father", "sister", "daughter", "son", "i", "me", "my",
                     "myself", "we", "our", "ours", "ourselves", "you", "you're", "you've", "you'll", "you'd", "your",
                     "yours", "yourself", "yourselves", "he", "him", "his", "himself", "she", "she's", "her", "hers",
                     "herself", "it", "it's", "its", "itself", "they", "them", "their", "theirs", "themselves", "what",
                     "which", "who", "whom", "this", "that", "that'll", "these",  "those", "am", "is", "are", "was",
                     "were", "be", "been", "being", "have", "has", "had", "having", "do", "does", "did", "doing", "a",
                     "an", "the", "and", "but", "if", "or", "because", "as", "until", "while", "of", "at", "by", "for",
                     "with", "about", "against", "between", "into", "through", "during", "before", "after", "above",
                     "below", "to", "from", "up", "down", "in", "out", "on", "off", "over", "under", "again", "further",
                     "then", "once", "here", "there", "when", "where", "why", "how", "all", "any", "both", "each",
                     "few", "more", "most", "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so",
                     "than", "too", "very", "can", "will", "just", "don", "don't", "should", "should've", "now",
                     "aren't", "couldn't", "didn't", "doesn't", "hadn't", "hasn't", "haven", "haven't", "isn't",
                     "mightn't", "mustn't", "needn't", "shan't",  "shouldn't", "wasn't", "weren't", "won't",
                     "wouldn't", "can't", "cannot", "yesterday", "today", "tomorrow"}
